extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-SF-TOKEN
        from_context: X-SF-TOKEN
        default_value: "${SPLUNK_ACCESS_TOKEN}"
  health_check:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:13133"
  http_forwarder:
    ingress:
      endpoint: "${SPLUNK_LISTEN_INTERFACE}:6060"
    egress:
      # endpoint: "${SPLUNK_API_URL}"
      # Use instead when sending to gateway
      endpoint: "${SPLUNK_GATEWAY_URL}"
  smartagent:
    bundleDir: "${SPLUNK_BUNDLE_DIR}"
    collectd:
      configDir: "${SPLUNK_COLLECTD_DIR}"
  zpages:
    #endpoint: "${SPLUNK_LISTEN_INTERFACE}:55679"
    expvar:
      enabled: true

  # Storage extension for storing filelog checkpoints.
  # Checkpoints allow the receiver to pick up where it left off in the case of a
  # collector restart.
  file_storage/filelogs:
    # Location where checkpoint files are stored. This directory must be writable
    # by the collector.
    directory: "${SPLUNK_FILE_STORAGE_EXTENSION_PATH}"
    compaction:
      on_start: true
      directory: /tmp/
    create_directory: true

receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      # System load average metrics https://en.wikipedia.org/wiki/Load_(computing)
      load:
      # Paging/Swap space utilization and I/O metrics
      paging:
      # Aggregated system process count metrics
      processes:
      # System processes metrics, disabled by default
      # process:

  otlp:
    protocols:
      grpc:
        endpoint: "${SPLUNK_LISTEN_INTERFACE}:4317"
        # Uncomment below config to preserve incoming access token and use it instead of the token value set in exporter config
        # include_metadata: true
      http:
        endpoint: "${SPLUNK_LISTEN_INTERFACE}:4318"
        # Uncomment below config to preserve incoming access token and use it instead of the token value set in exporter config
        # include_metadata: true

  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a Splunk APM customer, these metrics are included
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ["0.0.0.0:8888"]
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: 'promhttp_metric_handler_errors.*'
            action: drop
          - source_labels: [ __name__ ]
            regex: 'otelcol_processor_batch_.*'
            action: drop

  smartagent/processlist:
    type: processlist
  
  signalfx:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:9943"
    # Whether to preserve incoming access token and use instead of exporter token
    # default = false
    #access_token_passthrough: true

  nop:

  # apache: #removed as now using auto discovery
  #   endpoint: "http://localhost/server-status?auto"
  #   collection_interval: 10s

  ### File Logs Receivers - Start ###
  # Apache access log.
  # Configured using the LogFormat directive.
  # By default, date and time are in the 'day/Month/year:hour:minute:second zone' format.
  # See https://httpd.apache.org/docs/current/mod/mod_log_config.html#logformat
  filelog/apache-access:
    include: [ "/var/log/apache2/access.log" ]
    operators:
      - type: regex_parser
        regex: '^(?P<host>.+) (?P<remote_logname>.+) (?P<user>.+) \[(?P<time>.+)\] "(?P<method>.+) (?P<path>.+) (?P<protocol>.+)" (?P<code>\d+) (?P<size>\d+) "(?P<referer>.+)" "(?P<agent>.+)"$'
        timestamp:
          parse_from: attributes.time
          layout: '%d/%b/%Y:%H:%M:%S %z'
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs

  # Apache error log.
  # Configured using the ErrorLogFormat directive.
  # By default, date and time are in the locale-specific representation (%c in strftime).
  # See https://httpd.apache.org/docs/current/mod/core.html#errorlogformat
  filelog/apache-error:
    include: [ "/var/log/apache2/error.log" ]
    operators:
      - type: regex_parser
        regex: '^\[(?P<time>.+?)\] \[(?P<module>\w+):(?P<level>\w+)\] \[pid (?P<pid>\d+):tid (?P<tid>\d+)\] (?P<log>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%c' # locale specific
        severity:
          parse_from: attributes.level
          mapping:
            fatal: emerg
            error3: alert
            error2: crit
            info2: notice
      - type: move
        from: attributes.log
        to: body
      - type: retain
        fields:
          - attributes.module
          - attributes["log.file.path"]
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs

  # Syslog and messages log files.
  # These are not in the RFC3164 format.
  filelog/syslog:
    include: [ "/var/log/syslog"]
    operators:
      - type: regex_parser
        regex: '^(?P<time>.+?) (?P<hostname>\S+) (?P<program>[^ :\[]+)\[?(?P<pid>\d+)?\]?: (?P<log>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%b %e %H:%M:%S'
      - type: move
        from: attributes.log
        to: body
      - type: retain
        fields:
          - attributes.program
          - attributes["log.file.path"]
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs

  ### File Logs Receivers - End ###

processors:
  batch:
    metadata_keys:
      - X-SF-Token

  # Enabling the memory_limiter is strongly recommended for every pipeline.
  # Configuration is based on the amount of memory allocated to the collector.
  # For more information about memory limiter, see
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiter/README.md
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}

  # Detect if the collector is running on a cloud system, which is important for creating unique cloud provider dimensions.
  # Detector order is important: the `system` detector goes last so it can't preclude cloud detectors from setting host/os info.
  # Resource detection processor is configured to override all host and cloud attributes because instrumentation
  # libraries can send wrong values from container environments.
  # https://docs.splunk.com/Observability/gdi/opentelemetry/components/resourcedetection-processor.html#ordering-considerations
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true

  # Optional: The following processor can be used to add a default "deployment.environment" attribute to the logs and
  # traces when it's not populated by instrumentation libraries.
  # If enabled, make sure to enable this processor in a pipeline.
  # For more information, see https://docs.splunk.com/Observability/gdi/opentelemetry/components/resource-processor.html
  #resource/add_environment:
    #attributes:
      #- action: insert
        #value: staging/production/...
        #key: deployment.environment

  # The following processor is used to add "otelcol.service.mode" attribute to the internal metrics
  resource/add_mode:
    attributes:
      - action: insert
        value: "agent"
        key: otelcol.service.mode

exporters:
  # Traces
  otlp_http:
    traces_endpoint: "${SPLUNK_INGEST_URL}/v2/trace/otlp"
    headers:
      "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
    auth:
      authenticator: headers_setter
  # Metrics + Events
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    # api_url: "${SPLUNK_API_URL}"
    # ingest_url: "${SPLUNK_INGEST_URL}"
    # Use instead when sending to gateway
    api_url: http://${SPLUNK_GATEWAY_URL}:6060
    ingest_url: http://${SPLUNK_GATEWAY_URL}:9943
    sync_host_metadata: true
    correlation:

  # Entities (applicable only if discovery mode is enabled)
  otlp_http/entities:
    logs_endpoint: "${SPLUNK_INGEST_URL}/v3/event"
    headers:
      "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
    auth:
      authenticator: headers_setter

  # Logs
  splunk_hec:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel"
    sourcetype: "otel"
    profiling_data_enabled: false

  # Profiling
  splunk_hec/profiling:
    token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "${SPLUNK_INGEST_URL}/v1/log"
    log_data_enabled: false

  # Send to gateway
  otlp_http/gateway:
    endpoint: http://${SPLUNK_GATEWAY_URL}:4318

  otlp_grpc/gateway:
    endpoint: "${SPLUNK_GATEWAY_URL}:4317"
    tls:
      insecure: true
    auth:
      authenticator: headers_setter

  # Debug
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      encoding: json
      level: "debug"
      output_paths: [/media/data/logs/otel/collector.log]
      error_output_paths: [/media/data/logs/otel/collector.log]

  extensions:
  - headers_setter
  - health_check
  - file_storage/filelogs
  - http_forwarder
  - zpages
  - smartagent

  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters:
      # - otlp_http
      # - signalfx
      # Use instead when sending to gateway
      - otlp_http/gateway
      - signalfx

    metrics:
      receivers:
      - hostmetrics
      - otlp
      - signalfx
      # - apache #removed as now using auto discovery
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      # - signalfx
      # Use instead when sending to gateway
      - otlp_http/gateway
      # - splunk_hec # sends metrics to Splunk Enterprise via HEC

    metrics/internal:
      receivers:
      - prometheus/internal
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      - resource/add_mode
      # When sending to gateway, at least one metrics pipeline needs
      # to use signalfx exporter so host metadata gets emitted
      exporters:
      - signalfx

    logs/signalfx:
      receivers:
      - signalfx
      - smartagent/processlist
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - signalfx

    logs/entities:
      # Receivers are dynamically added if discovery mode is enabled
      receivers:
      - nop
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - otlp_http/entities

    logs:
      receivers:
      - otlp
      - filelog/apache-access
      - filelog/apache-error
      - filelog/syslog
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters:
      - splunk_hec
      # - splunk_hec/profiling
      # Use instead when sending to gateway
      # - otlp_http/gateway