extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-SF-TOKEN
        from_context: X-SF-TOKEN
        default_value: "${SPLUNK_ACCESS_TOKEN}"
  health_check:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:13133"
  http_forwarder:
    ingress:
      endpoint: "${SPLUNK_LISTEN_INTERFACE}:6060"
    egress:
      # endpoint: "${SPLUNK_API_URL}"
      # Use instead when sending to gateway
      endpoint: "${SPLUNK_GATEWAY_URL}"
  smartagent:
    bundleDir: "${SPLUNK_BUNDLE_DIR}"
    collectd:
      configDir: "${SPLUNK_COLLECTD_DIR}"
  zpages:
    #endpoint: "${SPLUNK_LISTEN_INTERFACE}:55679"
    expvar:
      enabled: true

  # Storage extension for storing filelog checkpoints.
  # Checkpoints allow the receiver to pick up where it left off in the case of a
  # collector restart.
  file_storage/filelogs:
    # Location where checkpoint files are stored. This directory must be writable
    # by the collector.
    directory: "${SPLUNK_FILE_STORAGE_EXTENSION_PATH}"
    compaction:
      on_start: true
      directory: /tmp/
    create_directory: true

receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      # System load average metrics https://en.wikipedia.org/wiki/Load_(computing)
      load:
      # Paging/Swap space utilization and I/O metrics
      paging:
      # Aggregated system process count metrics
      processes:
      # System processes metrics, disabled by default
      # process:

  otlp:
    protocols:
      grpc:
        endpoint: "${SPLUNK_LISTEN_INTERFACE}:4317"
        # Uncomment below config to preserve incoming access token and use it instead of the token value set in exporter config
        # include_metadata: true
      http:
        endpoint: "${SPLUNK_LISTEN_INTERFACE}:4318"
        # Uncomment below config to preserve incoming access token and use it instead of the token value set in exporter config
        # include_metadata: true

  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a Splunk APM customer, these metrics are included
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ["0.0.0.0:8888"]
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: 'promhttp_metric_handler_errors.*'
            action: drop
          - source_labels: [ __name__ ]
            regex: 'otelcol_processor_batch_.*'
            action: drop

  smartagent/processlist:
    type: processlist
  
  signalfx:
    endpoint: "${SPLUNK_LISTEN_INTERFACE}:9943"
    # Whether to preserve incoming access token and use instead of exporter token
    # default = false
    #access_token_passthrough: true

  nop:

  ### File Logs Receivers - Start ###
  # MySQL server error log. Contains critical errors that occurred during the
  # server's operation, table corruption, start and stop information.
  # When running under Systemd, error logging goes to journald. To enable
  # logging to a file, use the log_error variable.
  # See https://mariadb.com/kb/en/error-log/
  filelog/mysql-error:
    include: [ "/var/log/mysql/error.log" ]
    multiline:
      # e.g. "2023-10-09 13:40:48 0 [Note] ..."
      line_start_pattern: '^[\w-]+ [\d:.]+ \w+ \[\w+\]'
    operators:
      - type: regex_parser
        regex: '^(?P<time>.+?) \d+ \[(?P<level>\w+)\] (?P<log>[\s\S]*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'
        severity:
          parse_from: attributes.level
      - type: move
        from: attributes.log
        to: body
      - type: retain
        fields:
          - attributes["log.file.path"]
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs

  # MySQL general query log. Contains a log of every SQL query received from a
  # client, as well as each client connect and disconnect.
  # Disabled by default. To enable, use the general_log_file variable.
  # See https://mariadb.com/kb/en/general-query-log/
  filelog/mysql-query:
    include: ["/var/log/mysql/query.log", "/var/log/mysql/mysql.log"]
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z)\s+(?P<id>\d+)\s+(?P<type>\w+)\s+(?P<log>.+)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%fZ'
      - type: move
        from: attributes.log
        to: body
      - type: retain
        fields:
          - attributes["log.file.path"]
          - attributes.id
          - attributes.type
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs
  
  # MySQL slow query log. Contains a log of SQL queries that took a long time to perform.
  # Disabled by default. To enable, use the slow_query_log variable.
  # See https://mariadb.com/kb/en/slow-query-log/
  filelog/mysql-slow_query:
    include: [ "/var/log/mysql/mysql-slow.log" ]
    multiline:
      line_start_pattern: '^# Time: '
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs

  # Syslog and messages log files.
  # These are not in the RFC3164 format.
  filelog/syslog:
    include: [ "/var/log/syslog"]
    operators:
      - type: regex_parser
        regex: '^(?P<time>.+?) (?P<hostname>\S+) (?P<program>[^ :\[]+)\[?(?P<pid>\d+)?\]?: (?P<log>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%b %e %H:%M:%S'
      - type: move
        from: attributes.log
        to: body
      - type: retain
        fields:
          - attributes.program
          - attributes["log.file.path"]
    include_file_name: false
    include_file_path: true
    storage: file_storage/filelogs

  ### File Logs Receivers - End ###

  
        
# ## MySQL Specific Receivers - removed as now using auto discovery
#   smartagent/mysql:
#     type: collectd/mysql
#     host: 127.0.0.1
#     port: 3306
#     databases:
#       - name:
#     username: ${MYSQL_USER}
#     password: ${MYSQL_USER_PWD}

#   mysql:
#     endpoint: localhost:3306
#     username: ${MYSQL_USER}
#     password: ${MYSQL_USER_PWD}
#     collection_interval: 10s
#     initial_delay: 1s
#     statement_events:
#       digest_text_limit: 120
#       time_limit: 24h
#       limit: 250
#     metrics:
#       mysql.query.slow.count:
#         enabled: true
#       mysql.query.count:
#         enabled: true

processors:
  batch:
    metadata_keys:
      - X-SF-Token

  # Enabling the memory_limiter is strongly recommended for every pipeline.
  # Configuration is based on the amount of memory allocated to the collector.
  # For more information about memory limiter, see
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiter/README.md
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}

  # Detect if the collector is running on a cloud system, which is important for creating unique cloud provider dimensions.
  # Detector order is important: the `system` detector goes last so it can't preclude cloud detectors from setting host/os info.
  # Resource detection processor is configured to override all host and cloud attributes because instrumentation
  # libraries can send wrong values from container environments.
  # https://docs.splunk.com/Observability/gdi/opentelemetry/components/resourcedetection-processor.html#ordering-considerations
  resourcedetection:
    detectors: [gcp, ecs, ec2, azure, system]
    override: true

  # Optional: The following processor can be used to add a default "deployment.environment" attribute to the logs and
  # traces when it's not populated by instrumentation libraries.
  # If enabled, make sure to enable this processor in a pipeline.
  # For more information, see https://docs.splunk.com/Observability/gdi/opentelemetry/components/resource-processor.html
  #resource/add_environment:
    #attributes:
      #- action: insert
        #value: staging/production/...
        #key: deployment.environment

  # The following processor is used to add "otelcol.service.mode" attribute to the internal metrics
  resource/add_mode:
    attributes:
      - action: insert
        value: "agent"
        key: otelcol.service.mode

  metricstransform:
    transforms:
      - include: ^mysql\.
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: version
            new_value: opentelemetry collector {{version}}
      - include: ^system\.
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: version
            new_value: opentelemetry collector {{version}}

exporters:
  # Traces
  otlp_http:
    traces_endpoint: "${SPLUNK_INGEST_URL}/v2/trace/otlp"
    headers:
      "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
    auth:
      authenticator: headers_setter
  # Metrics + Events
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    # api_url: "${SPLUNK_API_URL}"
    # ingest_url: "${SPLUNK_INGEST_URL}"
    # Use instead when sending to gateway
    api_url: http://${SPLUNK_GATEWAY_URL}:6060
    ingest_url: http://${SPLUNK_GATEWAY_URL}:9943
    sync_host_metadata: true
    correlation:

  # Entities (applicable only if discovery mode is enabled)
  otlp_http/entities:
    logs_endpoint: "${SPLUNK_INGEST_URL}/v3/event"
    headers:
      "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"
    auth:
      authenticator: headers_setter

  # Logs
  splunk_hec:
    token: "${SPLUNK_HEC_TOKEN}"
    endpoint: "${SPLUNK_HEC_URL}"
    source: "otel"
    sourcetype: "otel"
    profiling_data_enabled: false

  # Profiling
  splunk_hec/profiling:
    token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "${SPLUNK_INGEST_URL}/v1/log"
    log_data_enabled: false

  # Send to gateway
  otlp_http/gateway:
    endpoint: http://${SPLUNK_GATEWAY_URL}:4318

  otlp_grpc/gateway:
    endpoint: "${SPLUNK_GATEWAY_URL}:4317"
    tls:
      insecure: true
    auth:
      authenticator: headers_setter

  # Debug
  debug:
    verbosity: detailed

service:
  extensions:
  - headers_setter
  - health_check
  - file_storage/filelogs
  - http_forwarder
  - zpages
  - smartagent

  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters:
      # - otlp_http
      # - signalfx
      # Use instead when sending to gateway
      - otlp_http/gateway
      - signalfx

    metrics:
      receivers:
      - hostmetrics
      - otlp
      - signalfx
      # MySql Specific Receivers
      # - smartagent/mysql # removed as now using auto discovery
      # - mysql # removed as now using auto discovery
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      - metricstransform
      exporters:
      # - signalfx
      # Use instead when sending to gateway
      - otlp_http/gateway
      # - splunk_hec # sends metrics to Splunk Enterprise via HEC

    metrics/internal:
      receivers:
      - prometheus/internal
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      - resource/add_mode
      # When sending to gateway, at least one metrics pipeline needs
      # to use signalfx exporter so host metadata gets emitted
      exporters:
      - signalfx

    logs/signalfx:
      receivers:
      - signalfx
      - smartagent/processlist
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - signalfx

    logs/entities:
      # Receivers are dynamically added if discovery mode is enabled
      receivers:
      - nop
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - otlp_http/entities

    logs:
      receivers:
      - otlp
      - filelog/mysql-error
      - filelog/mysql-query
      - filelog/mysql-slow_query
      - filelog/syslog
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters:
      - splunk_hec
      # - splunk_hec/profiling
      # Use instead when sending to gateway
      # - otlp_http/gateway